language: cpp
os: osx

notifications:
  email: false
cache:
- ccache

before_install:
- brew update
- brew install zmq zmqpp armadillo protobuf

script:
- mkdir cmake-build-debug && cd cmake-build-debug;
- cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Ninja" ..
- cmake --build . --target roboteam_proto -- -j 8

after_success:
- bash <(curl -s https://codecov.io/bash) -f roboteam_ai_coverage.info.cleaned || echo "Codecov did not collect coverage reports"
