# This travis image builds roboteam_suite and runs the target 'proto_tests'.
# All other repositories of roboteam_suite are set to the master branch.
# We need all dependencies to parse the cmake files. This can be optimized later,
# but with caching this is not a large performance hit anyway.

language: cpp
os: osx
osx_image: xcode11.2

addons:
  homebrew:
    packages:
      - zmq       # proto dependency
      - zmqpp     # proto dependency
      - protobuf  # proto dependency
      - armadillo # world dependency
      - ccache    # speeding up build
      - ninja     # speeding up build
      - qt        # roboteam_ai dependency

notifications:
  email: false
  slack:
    secure: DLX56Fc88/Md7ZEqRxK9DPeRQy7rQId2+3zBw83sjUAlifxO4bFCKoCNqiGZqETzWXNtHw/brmBs/ZwxV3/a5361I2IWn/JlB70lKUKEiGdR36aMYl8xFxK+DASXayPKHG+75xm04qh/7ktyPnX0NFGBOA6ETW2MSDZs9omohu85MlQ6abGOfIB0R7EwUaIttvj9YFwfroUtu5lsDDx3X5v2DQRvQXlicozWh4fpEQIh4TKQNpqR5wa/ig7YCPMq28Sm/EgOTNA99pg/oRcL66b98/6WHE1zMTGmhiA7mGGiKdvvwwliJHvDgDyoXCpGP9SxalgltNItXBXbMvi3a1N9IJ8FYVfbnnwP6sORmUw6jI5lzy9cuEkBH+awKPeS459Qj7RYoPc8vTs+MgAeUkP5UIBwt7Y3l51Co594gj2mbvl9j2HL0fXMIGmfWn7tG+n/mAeHYf+Mwp70D8g5qZfnivo5ERG387bIhzTDD0wFVBQfbSuKeNhE/bOvNvb1hOc0AHwojmpM/XP79A+JLT1rjszSZdUTFxzPfcx8qOGG/KmZKADKj+WRveeuwDDBw4v5kzrqX1DmppsCWiCNncS8fB7oZ4Z5I2CktlYJL3z0IMby/tPy6UpLlQlr9SvRRqGsg9Q5VhdrQA7Gi4jjgLTPt7aWWo95VYE6qQADcv0=

cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - $HOME/.ccache

# Install Google Test from source
install:
  - cd ~/
  - git clone https://github.com/google/googletest.git
  - cd googletest
  - mkdir install
  - cd install
  - cmake ../
  - make
  - sudo make install


# First we set up the compiler to use ccache.
# then clone roboteam_suite and put all repositories on master.
# then we replace roboteam_proto from rtt_suite with the branch you are currently on to test this branch specifically.
# As a temporary solution we currently need development of roboteam_ai since master has no mac support yet.
# Finally, we run the tests.
script:
  - cd ~
  - export CC="ccache gcc"
  - export CXX="ccache g++"
  - export CCACHE_SLOPPINESS=pch_defines,time_macros
  - git clone https://github.com/RoboTeamTwente/roboteam_suite roboteam_suite --recurse-submodules
  - cd ~/roboteam_suite
  - rm -rf roboteam_proto
  - git submodule foreach git checkout master
  - cd roboteam_ai            # ai has to be on development for some qt fixes
  - git checkout development  # ai has to be on development for some qt fixes
  - cd ..                     # ai has to be on development for some qt fixes
  - mv ${TRAVIS_BUILD_DIR} .
  - mkdir cmake-build-debug && cd cmake-build-debug;
  - cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Ninja" ..
  - cmake --build . --target proto_tests -- -j 8
  - cd roboteam_proto
  - ./proto_tests
