language: cpp
os: osx
osx_image: xcode11.2

addons:
  homebrew:
    packages:
      - gcc@7
      - zmq
      - zmqpp
      - protobuf
      - ccache

notifications:
  email: false

cache:
  directories:
    - $HOME/Library/Caches/Homebrew

script:
- export CC="ccache gcc"
- export CXX="ccache g++"
- mkdir cmake-build-debug && cd cmake-build-debug;
- cmake ..
- cmake --build . --target proto_tests -- -j 8
