language: cpp
os: osx
osx_image: xcode11.2

notifications:
  email: false

before_cache:
  - brew cleanup

cache:
  directories:
    - $HOME/Library/Caches/Homebrew

before_install:
- brew update
- brew install zmq zmqpp protobuf

script:
- mkdir cmake-build-debug && cd cmake-build-debug;
- cmake ..
- cmake --build . --target proto_tests -- -j 8
